### ISSUE TITLE
Multiple-letter violation codes are not displayed by Vim Syntastic syntax checker

### ISSUE THREAD

**Issue by myii** [AlexvEck/flake8-class-newline#2]
**This is not a bug with your plugin** but I'm raising this here for your awareness, since you use multiple-letter violation code(s).

I've filed an issue with `vim-syntastic`: https://github.com/vim-syntastic/syntastic/issues/2163.

The resolution of that bug may be of interest to you.  If not, please disregard this report, with my apologies.

**Comment by alexandervaneck** [comment]
Hi @myii,

Thank you for bringing this to my attention! 👍 

Technically we could change the CNL100 violation code to CNL1. It would be 4 characters and compliant. What do you think?

**Comment by myii** [comment]
@AlexanderVanEck You're welcome.

Actually, the problem is not the length of the code but that it uses 3 letters at the beginning rather than one.  For Syntastic, it will still fail with `CNL1`, the same way it fails with `CNL100`.

But there is nothing wrong with using the 3 letters, since Flake8 3.0+ allows this and other plugins are doing the same thing.

Syntastic is looking for a fixed format that begins with 1 letter only.  It is time for them to upgrade their `flake8.vim` to be able to deal with these new formats.

**Comment by alexandervaneck** [comment]
Ah ok. Seems like a won't fix for flake8-class-newline then.

Thanks again, appreciate it 👍

**Comment by myii** [comment]
@AlexanderVanEck No problem, `wontfix` is exactly right.  Just for your information, in case you get any users complaining that your plugin isn't working with Vim, Atom, etc.  It isn't your fault but rather the editor syntax checkers need updating.

By the way, thanks for developing your plugin!
